import type { Metadata } from 'next'
import './globals.css'
import Container from '@/app/components/Container'
import Footer from '@/app/components/Footer'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className="bg-zinc-50 antialiased">
                <Container>
                    {children}
                    <Footer />
                </Container>
            </body>
        </html>
    )
}
